### ISSUE TITLE
Sending Multiple AT Commands

### ISSUE THREAD

**Issue by jbgtenn423** [4IceG/luci-app-atinout-mod#1]
Was wanting to know if it is possible to send multiple commands on one line? I use this to lock bands and was needing to send reboot modem command after.

**Comment by 4IceG** [comment]
Hi, Please try to type the command to send "AT command;AT command" into the command window. I don't remember if I tested such commands, I would have to try, I always gave them individually. I know that if something can't be saved at this point because ';' I used as a separation between description and command, so I would have to change the symbol here.

**Comment by jbgtenn423** [comment]
![image](https://user-images.githubusercontent.com/55149461/97990613-370c4c80-1dae-11eb-9194-06fd7ed3a5a6.png)

I tried to run AT;AT in manual command box but it seem to run the first only then  2nd AT command is trying to be run as a shell command as shown in png I uploaded

**Comment by 4IceG** [comment]
So it remains to enter the AT commands individually, the "AT+CFUN=1.1"
command itself should restart the modem.

2020-11-03 14:28 GMT+01:00, jbgtenn423 <notifications@github.com>:
