### ISSUE TITLE
Repo?

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-atinout-mod#11]
Hi, thanks for this.
Do you have any repo similar to http://openwrt.132lan.ru/packages/?

**Comment by 4IceG** [comment]
Hi, sorry but I don't have such a repository. I don't compile packages for other architectures (because it wouldn't be able to check them).

You can try using socat instead of atinout.
https://github.com/4IceG/luci-app-socat/releases/latest

https://github.com/4IceG/luci-app-socat/releases/download/1.1-2021-10-30/luci-app-socat_1.1-2021-10-30_all.ipk

**Comment by bam80** [comment]
Thanks. Just a note I most interested in arch-indepentent Luci packages such as this.
Having a repo would allow to easy install/update etc.

**Comment by bam80** [comment]
Just found https://dl.eko.one.pl/openwrt-22.03/packages/mipsel_24kc/luci/
Isn't it a good candidate for this app to be placed to? (probably should be just platform-agnostic)

**Comment by 4IceG** [comment]
Hi,
Localization good, but I have no influence on what Cezary compiles. Maybe he thinks that there are already packages to support AT commands and a new one is not needed.
